name: Build Gatsby Site

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          
      - name: Install dependencies
        run: npm install
      
      - name: Build Gatsby site
        run: npm run build
      - name: Send Slack Notification
        if: success()
        uses:
     rtCamp/action-slack-notify@v3.0
        with:
          status: 'success'
          slack_bot_token: $
     {{ secrets.SLACK_BOT_TOKEN }}
          channel_id: 'C050D8HTPK5'
          message: 'The build is successful'
